### ISSUE TITLE
Register projects to the tea protocol

### ISSUE THREAD

**Issue by johnslavik** [shellm-org/granary#4]
https://tea.xyz/
https://docs.tea.xyz/tea-white-paper/white-paper

**Comment by johnslavik** [comment]
@pawamoy

**Comment by pawamoy** [comment]
Super interesting, thanks! Too bad they don't have a white-paper for the ranking algorithm yet.

**Comment by pawamoy** [comment]
I'm a bit skeptical about the blockchain/coin stuff, and I don't see the tea protocol mentioned a lot on the web. It seems to be [backed by Binance](https://techcrunch.com/2022/12/06/from-the-creator-of-homebrew-tea-raises-8-9m-to-build-a-protocol-that-helps-open-source-developers-get-paid/?guccounter=1) (among others).

The app is super gamified (which is both good and bad haha). Out of all dependents and dependencies of for example mkdocstrings, none is register on the site. It was announced one year ago: still not a lot of traction? Did it just launch? Hackernews didn't comment a lot about it. There seems to be only 253 registered OSS projects yet.

**Comment by pawamoy** [comment]
Tea does not support the shell ecosystem (Basher is not one of their supported package managers), and there doesn't seem to be a way to ask for its support.

**Comment by johnslavik** [comment]
> It was announced one year ago: still not a lot of traction? Did it just launch? Hackernews didn't comment a lot about it. There seems to be only 253 registered OSS projects yet.

Indeed, the tea project is very new. I posted this as a suggestion. I got to know about it from jaraco who works with them.

**Comment by pawamoy** [comment]
OK, thanks for the info, that's a bit reassuring.

I'm finding more weird stuff though: tea also has a goal of providing some kind of universal package manager. It's called pkgx. Their website has a list of projects, but...

https://pkgx.dev/pkgs/atuin.sh/

![atuin](https://github.com/shellm-org/granary/assets/3999221/334acc5f-b032-46c3-8773-a6f2917c4548)

https://pkgx.dev/pkgs/github.com/squidfunk/mkdocs-material/

![mkdocsmaterial](https://github.com/shellm-org/granary/assets/3999221/8da3fe9e-63a4-4a33-b156-84da171135b9)

What the hell is that?? Sounds (badly) auto-generated by IA?

**Comment by pawamoy** [comment]
I'll close this because there's nothing we can do for shell projects (yet), and I'm not even sure I'd want to use tea (it looks a bit scammy/dodgy IMO :confused:). If you find articles about it though, or interactions between the authors and the community, I'd be happy to read them :slightly_smiling_face:

**Comment by johnslavik** [comment]
Sure! I'll reopen if I get to know about anything interesting we can do with tea. Thanks for your time & feedback @pawamoy.

**Comment by pawamoy** [comment]
https://connortumbleson.com/2024/02/26/the-disappointing-tea-xyz/
